name: Build and deploy GH Pages

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          # Using GITHUB_TOKEN since we're deploying to the same repo
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
